# Generated by Django 3.2.3 on 2023-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20230323_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='house_photo/'),
        ),
    ]
